
import type { z } from 'zod';
import type React from 'react';

export type WasteCategory =
  'ewaste' |
  'plastic' |
  'biowaste' |
  'cardboard' |
  'paper' |
  'glass' |
  'metal' |
  'organic' |
  'other' |
  'plasticOther' |
  'plasticPete' |
  'plasticHdpe' |
  'plasticPp' |
  'plasticPs' |
  'recyclable' |    // New broad category
  'compostable' |   // New broad category
  'non-recyclable'; // New broad category


export interface ClassificationRecord {
  id: string;
  imageDataUri: string;
  category: WasteCategory; // Will now store 'recyclable', 'compostable', or 'non-recyclable' from AI
  confidence: number;
  timestamp: number;
  points?: number;
}

// Firestore Data Structures
export interface WasteEntry {
  id?: string; // Auto-generated by Firestore
  userId: string;
  timestamp: number; // Store as Unix timestamp (number) for easier querying
  type: WasteCategory; // Can be specific or broad depending on how it's logged
  quantity: number;
  unit: 'items' | 'kg' | 'g' | 'count'; // Added count for generic items
  imageUrl?: string;
  notes?: string;
  location?: { // Optional for location-based filtering
    latitude: number;
    longitude: number;
  };
}

export interface UserProfile {
  id: string; // Corresponds to Firebase Auth UID
  displayName: string;
  email?: string;
  avatar?: string; // data URI or link to an image
  score: number; // Total points
  co2Managed: number; // CO2 managed in Kg
  
  // Detailed waste counts - these will NO LONGER be updated by the AI classification flow directly.
  // They might be updated by manual logging or other mechanisms if implemented.
  totalEwaste: number;
  totalPlastic: number;
  totalBiowaste: number;
  totalCardboard: number;
  totalPaper: number;
  totalGlass: number;
  totalMetal: number;
  totalOrganic: number;
  totalOther: number;
  totalPlasticOther: number;
  totalPlasticPete: number;
  totalPlasticHdpe: number;
  totalPlasticPp: number;
  totalPlasticPs: number;
  
  itemsClassified: number; // Overall count of all items
  challengesCompleted: number;
  badges?: string[];
  scheduleNotificationLocation?: string;
  scheduleNotificationsEnabled?: boolean;
}

// For Gamified Reduction Challenges
export interface Challenge {
  id: string; 
  title: string;
  description: string;
  points: number;
  badgeIcon?: string; 
  badgeName?: string; 
  type: 'reduce_category_by_percentage' | 'log_specific_item_count' | 'daily_login' | 'overall_reduction';
  categoryGoal?: WasteCategory; // This might refer to old specific categories or new broad ones
  targetValue: number; 
  unit?: '%' | 'items' | 'days';
  durationDays?: number; 
  isActive: boolean;
  createdAt: number; 
}

export interface UserChallengeProgress {
  challengeId: string;
  userId: string;
  currentProgress: number;
  targetValue: number; 
  completed: boolean;
  completedAt?: number; 
  startedAt: number; 
  lastUpdatedAt: number; 
}


// For Community Reuse Marketplace
export interface MarketplaceItem {
  id: string;
  userId: string; 
  title: string;
  description: string;
  itemCategory: WasteCategory | 'furniture' | 'clothing' | 'books' | 'food' | 'other_reuse';
  imageDataUri?: string;
  imageUrl?: string; 
  dataAiHint?: string; 
  postedAt: number;
  postedByDisplayName: string; 
  status: 'available' | 'reserved' | 'taken';
  location?: string; 
  contactInfo?: string;
}


// Form input types
const loginSchema = z.object({
  email: z.string().email(),
  password: z.string().min(6),
});
export type LoginFormInputs = z.infer<typeof loginSchema>;

const signupSchema = z.object({
  name: z.string().min(2),
  email: z.string().email(),
  password: z.string().min(6),
  confirmPassword: z.string().min(6),
}).refine((data) => data.password === data.confirmPassword, {
  message: "Passwords don't match.",
  path: ['confirmPassword'],
});
export type SignupFormInputs = z.infer<typeof signupSchema>;

// For IoT Smart Bin Integration
export interface BinLocation {
  latitude: number;
  longitude: number;
}

export interface BinData {
  id: string;
  location: BinLocation;
  fill_level: number; // 0-100
  lastEmptied: number; // timestamp
  notify: boolean;
  battery_level?: number; // Optional: 0-100
  last_updated?: number; // Optional: timestamp of last data sync from bin
}

// For Bin1 Fill Level History
export interface Bin1FillLevelHistoryPoint {
  index: number;
  fill_level: number;
}


// For Recycling Schedules
export interface RecyclingScheduleItem {
  id: string;
  date: string; 
  wasteType: 'recycling' | 'compost' | 'trash' | 'yard_waste' | string; 
  notes?: string;
}

export interface UserScheduleSettings {
  locationQuery: string; 
  notificationsEnabled: boolean;
  lastFetched?: number; 
  schedules?: RecyclingScheduleItem[];
}

// For 5 Rs Tips (Used in History Page and Classification Dialog)
export interface TipInfo {
  title: string;
  icon: React.ElementType;
  definition?: string;
  fiveRs: {
    reduce: string;
    reuse: string;
    recycle: string;
    educate: string;
    support: string;
  };
}

// For E-Waste Dashboard (Simulated)
export type EWasteCategory = 'batteries' | 'mobiles' | 'laptops' | 'others';

export interface RealTimeEWasteDataPoint {
  timestamp: string; // HH:MM:SS
  volume: number; // kg or %
}

export interface EWasteCategoryDistributionPoint {
  name: Capitalize<EWasteCategory> | 'Other E-Waste';
  value: number;
  fill: string;
}

export interface MonthlyEWasteDataPoint {
  month: string; // e.g., "Jan", "Feb"
  volume: number; // kg
}
